monoisotopic_masses = {
    'A': 71.03711,  # Alanine
    'R': 156.10111, # Arginine
    'N': 114.04293, # Asparagine
    'D': 115.02694, # Aspartic Acid
    'C': 103.00919, # Cysteine
    'E': 129.04259, # Glutamic Acid
    'Q': 128.05858, # Glutamine
    'G': 57.02146,  # Glycine
    'H': 137.05891, # Histidine
    'I': 113.08406, # Isoleucine
    'L': 113.08406, # Leucine
    'K': 128.09496, # Lysine
    'M': 131.04049, # Methionine
    'F': 147.06841, # Phenylalanine
    'P': 97.05276,  # Proline
    'S': 87.03203,  # Serine
    'T': 101.04768, # Threonine
    'W': 186.07931, # Tryptophan
    'Y': 163.06333, # Tyrosine
    'V': 99.06841   # Valine
}

def calculateProteinMass(protein):
    result = 0.0
    for item in protein:
        if item in monoisotopic_masses:
            result+= monoisotopic_masses[item]

    print(result)
# protein = "SKADYEK"
protein = "FYPPQWMTKAEQFIMNVKCPSAHTRNCNGCLPHMLYYFNFKQAEVIQFYKLDMKTQKAWWTKSDPTQCATTSNACHNKPFQKEKGDMDWNLQSACKQKFFRQTTLSFQCNCDSCHNAKVITGQIADYLQSYDAIFVSDPFFKTSYFCVTWGGKNPRGDQWGSFKWKPYSRFSEFEWRAGYNGQQESLFEAERMNLWYGPCYRVSNWFKRHRALKYMWCGHCDVCGVGALAREILNIWTLFQEHRRENSPHEFIDQYTDASTKICQNFCGWTQTHNVNLIQEKMSADPSIIVCWMLDDVDCAGCHNHASYPWIATMYKAYGPIVFKVWGNFNDYDRLLIWHYVDNMSVWFLVDYLAPHTADADFFMCWKQMEGCIYQEGNMWSHGGTLHGWTDCNLKHCPLHGSLSQPYLCLNDHIICEPDYHMHHSHRLRWFWCHVANPFVCLDDNQCTASKKNWMFDYHSNLHETMTMEFFRTVHEGSIYDHQQNVPMGWFVCSTGVHGHDHMARYKIPSDVMQPVVGIWEKLKDNEEEPPMSIDIWASIGFYYYSSINQFITSFDADLYQAMGPQSVWTMSQGISIPKEWFHDMWAFKAKYSDDRILWECWECSTCKNTGWHNIENTMPNDNYMIWMRPKCDSARHTSSIQCHRCVDSDFQIPHQMRFDTGYWKYFLGRPSSMGQMVSTRMIINRKTANQEYMHRQYCLWIEIIITMWWINFVTAMPHKWNKWWLQIGNKHVCSASWRPHQQCRHARGQGTDSETVPFKWDKIQKYCCAWRRPLSQMFAESGRGAYYDMPKYCADPCAMMEQTTKTDHYVFKGGSDFASHMEEPAYWWL"
print(calculateProteinMass(protein))
