import sys
 
dna="TCCATTTGGTCTGTATGGCAGCCCGCGAACAAGATCTCACGGAGGGTACTAACTTATGGTGAGTTACTTTCCACTAGATTAGTGCATCCCACTGAACGCTATCTCAGGGTTTCCTTTCCGCTCACGTTATCCGGCCTCTAACACTGGACGAAGTTGATTCGGTAAAAAAGTGGAAACGGTCTAGCACTTCCCGCCCCTGTCGGACGCCGTCAGATCGAAGGAAGACTGTAGCTCCCCTTTCACTACCAGGTAGCGCGGACCGTAGGTAGTCTTGGCAAACACACATCGACAAGAAAGCTCAGTCACGAGAGAGACCCACGCCGCTGAGGATTACTAAGCGTAACGAAGTCAGAAAACTGAAAGCCCGGTAACTGCTAAAGGCTTCCAAAGGATTCCCCAAATTATAGCCTTAAAGAGGGTCATGTTCCTCCCGGCATAGCTCGAGGTGGACACTTTCCCGGATATGATCAAACACGAGTAATGAAGATAGACTGGCTAAGATAGACGCTTGCAGGACCATAATCGCTCTTGTACAAGTAAGTGCGTTTATTGGTAGCTATAAATGCGACGGTGGAAGGCTTTTTTTACAAGCCTGTTGAAGGACATACTACCGGGCTCCATATGGCTAGCGAGAACGCTGCCCCTTGCTGAGACCTGGATCTTTGTTAAGGTAACGATCTTGAATTTCAGTATGCCCCGAGCTCAGGGTACCGATGCGACTGACTTCTACGCGATAAGGACGACTTCCGGTTTAGGGCTGTGTAGAAGTTAGGGCGTCATGCTCTTCTCAAAAGGGCACAACGGGCGACTCGCACGTTCTGTCGTACTATAAATGTCGCTTCTCCCGCCTCCTGTGCGCTGGTGTAGCTACCGCTTGTCGAGCAGGTCTGTAGCCGTGCGGAATAGTAGCTAAGTGACTGGCGATTTTACCGCAGCTATGTTGTGCGATCTAGGCAGCGGACC"

def countDNANucleotides(input_str):
    count_A = 0
    count_C = 0
    count_G = 0
    count_T = 0
    for c in input_str:
        if c == 'A':
            count_A += 1
        elif c == 'C':
            count_C += 1
        elif c == 'G':
            count_G += 1
        elif c == 'T':
            count_T += 1
        
    print(str(count_A) + " " + str(count_C) + " " + str(count_G) + " " + str(count_T))
    

    
print(countDNANucleotides(dna), end="")
