def findMotif(subdna,dna):
    len_subdna = len(subdna)
    limit = len(dna) - len_subdna
    index_arr = []
    for i,c in enumerate(dna[:limit-1]):
        for j, x in enumerate(subdna):
            if x != dna[i+j]:
                break
            if j == len_subdna -1:
                index_arr.append(i+1)

    output = ""
    for item in index_arr:
        output += str(item) + " "
    print(output)
    
dna="AAGACGCAAAAGGGAGACGCAAGACGCAGAGAGACGCAACTTCAAGACGCAGTTTAGACGCATCGTTAAGACGCAGCATAAAAGACAGACGCACCATAGACGCACTACTCAGACGCAGAGACGCAATTTAGACGCAAGACGCAGAGACGCAAGACGCAAGTCGTACGAAACGCAAGTAGACGCATAGACGCAGGGGTATGAGACGCAAGACGCATTTAAGACGCAAGACGCACAGACGCAAAGACGCACCCACAGACGCATGAAGACGCAAGACGCAAGTTGAGACGCAAAATAAAGAGACGCATTGAGAAGACGCAAACGCAGTAGACGCAGGTCTTAGACGCACCAAAGACGCACGAGACGCAAGACGCAAGACGCAAGACGCATAGACGCAGCAGACGCAAGACGCATCAGACGCAAGACGCAAGAGACGCATTGGTAAGACGCACACAGACGCAACGGAAGACGCAGTCACACAGACGCATTAGACGCAAGACGCACGAGACGCACTATGCCCGAAGACGCATAGACGCAAGACGCATGAAGACGCAAGACGCATCAGACGCAAGACGCACTTGAGACGCATGTTTTAGACGCAGTGCTTCTACCGAGACGCAACCATGGCGCAGACGCATTCTGACGCTTGTAGTACAGAGACGCAAGACGCAAGACGCATGAGACGCAGAAGACGCAAGACGCAGTGAGACGCATGAGACGCAAGACGCAGGAGACGCAAAGACGCAGAGACGCACAAGGAGACGCAGCGGCCTAACACAGCAGACGCAGAAGACGCAGACAGGGGTAGACGCAAGACGCAAGTTGCCAGACGCAGTAGACGCAAGACGCATAGACGCAGAGACGCATAGAAGCACTTAGAGACGCATACAGACGCACAGACGCATAGACGCAAGACGCAAGTTTAGACGCAATAGACGCACCCAGACCC"
subdna="AGACGCAAG"


print(findMotif(subdna,dna))
